### PR TITLE
fix(mp4Inspector): read version 1 sidx boxes

### LINKED ISSUE #287: Incorrectly parsing SIDX box
Hi, there seems to be a bug with parsing the `SIDX` box from the mp4. I looked into the function that parses the SIDX and I believe this is where the bug exists.
https://github.com/videojs/mux.js/blob/b8df0af5f003b84267064789b3f0421d8f00f7cd/lib/tools/mp4-inspector.js#L390
The issue seems to be the way the  `earliestPresentationTime` and `firstOffset` are being parsed. In the `ISO/IEC 14496-12:2012` spec, in section `8.16.3.2`, the syntax dictates that the properties `earliestPresentationTime` and `firstOffset` are 64 bit values if the version is set to the value of `1`. They are 32 bit values if  the version is `0`. It looks like in your code, it assumes that those properties are always parsed as 32 bit values. I know it's not possible to represent a 64 bit integer in Javascript since it is limited to 53 bits. Our solution was to just parse 53 bits and move the index 8 bytes. We also log a warning message that only 53 bits of the value are being parsed.

### PR DESCRIPTION
**Pull request by ldayananda**
Should resolve #287.

### CODE REVIEW

File: lib/tools/mp4-inspector.js [hunk 1]
```diff
@@ -445,14 +445,53 @@ var
...
-      for (i = 24; referenceCount; i += 12, referenceCount--) {
+      if (result.version === 0) {
+        earliestPresentationTime = view.getUint32(i);
+        i += 4;
+        firstOffset = view.getUint32(i);
+        i += 4;
+      } else {
+        // read 64 bits
+        earliestPresentationTime = view.getUint32(i);
+        earliestPresentationTime *= Math.pow(2, 32);
```
Comment (amotzte) [inline lib/tools/mp4-inspector.js]: Regular integer in javascript is 52 bits. Might want to use [BigInt](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt) for 64 bits number.

Comment (gkatsev) [reply lib/tools/mp4-inspector.js]: Unfortunately, browser compatibility doesn't allow us to use BigInt yet. However, since we're working with Uint32 array views, we should still be able to access the full value.

**Review by brandonocasey — APPROVED** [review]

File: lib/tools/parse-sidx.js [hunk 2]
```diff
@@ -1,18 +1,34 @@
...
+    i += 16;
+  }
+
+  i += 2; // reserved
+
+  var referenceCount = view.getUint16(i);
+
+  i += 2; // start of references
+
+  for (i; referenceCount; i += 12, referenceCount--) {
```
Comment (gesinger) [inline lib/tools/parse-sidx.js:31]:
```suggestion
  for (; referenceCount > 0; i += 12, referenceCount--) {
```

**Review by gesinger — APPROVED** [review]
Looks good, but one style suggestion (though not required)

**Comment by brandonocasey** [comment]
accidentally merged this into master. I cherry picked this into main and reverted the change in master.

**Comment by brandonocasey** [comment]
Fixes https://github.com/videojs/http-streaming/issues/909
